name = "Julianalyses"
uuid = "a75bd7e6-2516-4e81-8f1b-017f9603ea27"
version = "0.1.0"
authors = ["Arnaud Spiwack"]

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Cairo = "1.1.1"
DataFrames = "1.8.1"
DuckDB = "1.4.1"
Fontconfig = "0.4.1"
LanguageServer = "4.5.1"
Plots = "1.41.2"
Revise = "3.12.3"
RollingFunctions = "0.8.1"
StatsPlots = "0.15.8"
TOML = "1.0.3"
